###
POST localhost:9090/api/onlyrequest

{
    "name": "John",
    "age": 30
}

###
POST localhost:9090/api/stringbody

{
    "name": "John",
    "age": 30
}
###

POST localhost:9090/api/mapbody
Content-Type: application/json

{
    "name": "John",
    "age": 30
}

###
GET localhost:9090/api/throw?throwParam=1

###
GET localhost:9090/api/throw


